name: vmtorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.1
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cachecontrol=0.14.1
  - cachecontrol-with-filecache=0.14.1
  - cairo=1.18.0
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cleo=2.2.1
  - click=8.1.7
  - click-default-group=1.2.4
  - cloup=3.0.5
  - colorama=0.4.6
  - crashtest=0.4.1
  - cython=3.0.11
  - dav1d=1.2.1
  - decorator=5.1.1
  - distlib=0.3.9
  - dulwich=0.21.7
  - ffmpeg=5.1.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=1.0.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glcontext=3.0.0
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - isosurfaces=0.1.2
  - jaraco.classes=3.4.0
  - jinja2=3.1.4
  - keyring=24.3.1
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.4
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libpng=1.6.44
  - libsqlite=3.47.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.4
  - manim=0.18.1
  - manimpango=0.6.0
  - mapbox_earcut=1.0.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - moderngl=5.11.1
  - moderngl-window=2.4.1
  - more-itertools=10.5.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multipledispatch=0.6.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4.2
  - numpy=1.26.4
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pango=1.54.0
  - pcre2=10.44
  - pexpect=4.9.0
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.43.4
  - pkginfo=1.11.2
  - platformdirs=4.3.6
  - poetry=1.8.4
  - poetry-core=1.9.1
  - poetry-plugin-export=1.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycairo=1.27.0
  - pycparser=2.22
  - pydub=0.25.1
  - pyglet=1.5.27
  - pygments=2.18.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyproject_hooks=1.2.0
  - pyrr=0.10.3
  - pysocks=1.7.1
  - python=3.11.10
  - python-build=1.2.2.post1
  - python-fastjsonschema=2.21.0
  - python-installer=0.7.0
  - python_abi=3.11
  - pytorch=2.2.2
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - scipy=1.14.1
  - screeninfo=0.8.1
  - setuptools=75.5.0
  - shellingham=1.5.4
  - six=1.16.0
  - skia-pathops=0.8.0.post2
  - srt=3.5.3
  - svgelements=1.9.6
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tk=8.6.13
  - tomli=2.2.1
  - tomlkit=0.13.2
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - trove-classifiers=2024.10.21.16
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - virtualenv=20.28.0
  - watchdog=6.0.0
  - wheel=0.45.0
  - x264=1!164.3095
  - x265=3.5
  - xattr=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - anyio==4.6.2.post1
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - comm==0.2.2
      - contourpy==1.3.1
      - coverage==7.6.7
      - cycler==0.12.1
      - debugpy==1.8.8
      - defusedxml==0.7.1
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fonttools==4.55.0
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - ipykernel==6.29.5
      - ipython==8.29.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.9.28
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numba==0.60.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - pure-eval==0.2.3
      - pyparsing==3.2.0
      - pypulseq==1.4.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pywavelets==1.7.0
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.21.0
      - send2trash==1.8.3
      - sigpy==0.1.26
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tornado==6.4.1
      - tqdm==4.67.0
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13

