name: bmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pip
  - pip:
      - pypulseq
      - jupyterlab
      - ipywidgets
      - torch
      - torchvision
      - torchaudio