name: bmc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - torch
  - tqdm
  - ipykernel
  - jupyter
  - pyyaml
  - pyqt6
  - pip
  - pip:
    - manim
    - pypulseq
    - jupyterlab
    - ipywidgets
    - torch
    - torchvision
    - torchaudio