####################################################################################
# ------ Simulation settings for (py)pulseq-cest BlochMcConnell simulations ------ #
# ------------------------ https://pulseq-cest.github.io/ ------------------------ #
####################################################################################

# sources/references for settings in this file:
# https://onlinelibrary.wiley.com/doi/abs/10.1002/mrm.26133

###### Pool settings
#  f: relative pool size fraction (float)
# r1: inverse longitudinal relaxation time R1 = 1/T1 [Hz] (float)
# r2: inverse transversal relaxation time R2 = 1/T2 [Hz] (float)
#  k: exchange rate [Hz] to water pool (MT and CEST pools only) (float)
# dw: chemical shift (delta omega) relative to water [ppm] (MT and CEST pools only) (float)

water_pool: {
  f: 1,
  t1: 2,
  t2: 0.05
}

# CEST
cest_pool: {  
 'amide': {
   f: 0.0045, # 72e-3 / 111,
   t1: 5,
   t2: 0.01,
   k: 150,
   dw: 10
  }
}

###### Scanner settings
#       b0: field strength [T] (float)
#    gamma: gyromagnetic ratio [rad / uT], default is 267.5153 (float)
# b0_inhom: field inhomogeneity [ppm], default is 0.0 (float)
#   rel_b1: relative amp inhomogeneity, default is 1.0 (float)

b0: 17
gamma: 267.5153
b0_inhom: 0.0
rel_b1: 1

##### Additional simulation settings
#           verbose: verbose output, default is False (bool)
#    reset_init_mag: True to reset magnetization after each readout, default is True (bool)
#             scale: relative magnetization after reset of magnetization, default is 1 (float)
# max_pulse_samples: maximum number of samples for each shaped rf pulse, default is 500 (int)
verbose: False
reset_init_mag: True
scale: 1
max_pulse_samples: 300
